# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define 'unit' do |unit|
    unit.vm.box = 'openvswitch'

    unit.vm.provider 'virtualbox' do |vb|
      vb.memory = '8192'
    end

    unit.vm.provision :shell, inline: 'sudo brctl addbr test'
  end
end
