# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define 'contract' do |contract|
    contract.vm.box = 'openvswitch'

    contract.vm.network 'private_network', ip: '192.168.205.9'

    contract.vm.provider 'virtualbox' do |vb|
      vb.memory = '8192'
    end

    contract.vm.provision :shell, path: 'install-docker.sh'
    contract.vm.provision :file, source: 'config.json', destination: '/opt/consul/config/config.json'
    contract.vm.provision :shell, inline: 'sudo systemctl start consul'
    contract.vm.provision :shell, inline: 'sudo systemctl enable consul'
  end
end
