# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define 'ovs' do |ovs|
    ovs.vm.box = 'centos/7'

    ovs.vm.provider 'virtualbox' do |vb|
      vb.memory = '8192'
    end

    ovs.vm.provision :shell, path: 'install-ovs.sh'
  end
end
