# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define 'host1' do |host1|
    host1.vm.box = 'centos/7'

    host1.vm.network 'private_network', ip: '192.168.205.10'

    host1.vm.provider 'virtualbox' do |vb|
      vb.memory = '8192'
    end

    host1.vm.provision :shell, inline: 'sudo mkdir -p /opt/consul/config && sudo chmod 777 /opt/consul/config'
    host1.vm.provision :file, source: 'watch_handler.sh', destination: '/opt/consul/config/handler'
    host1.vm.provision :file, source: 'config.json', destination: '/opt/consul/config/config.json'
    host1.vm.provision :shell, path: 'bootstrap.sh'
  end

  config.vm.define 'host2' do |host2|
    host2.vm.box = 'centos/7'

    host2.vm.network 'private_network', ip: '192.168.205.11'

    host2.vm.provider 'virtualbox' do |vb|
      vb.memory = '8192'
    end

    host2.vm.provision :shell, inline: 'sudo mkdir -p /opt/consul/config && sudo chmod 777 /opt/consul/config'
    host2.vm.provision :file, source: 'watch_handler.sh', destination: '/opt/consul/config/handler'
    host2.vm.provision :file, source: 'config.json', destination: '/opt/consul/config/config.json'
    host2.vm.provision :shell, path: 'bootstrap.sh'
  end
end
