---
version: '2'
services:
  runner:
    image: ansible-runner:latest
    ports:
      - 8080:8080
    volumes:
      - ../ovs-vagrant/ssh-config:/root/.ssh/config
      - ../ovs-vagrant/.vagrant/machines:/root/ovs-vagrant/.vagrant/machines
    environment:
      - APP_PLAYBOOK_PATH=playbook
      - APP_PLAYBOOK_NAME=site.yml
